apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: derrainaho/demo-app:python-app-2.0
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: registrypullsecret 
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: demo-app
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
  externalIPs:
    - 10.39.0.4

