apiVersion: v1
kind: Secret
metadata:
  name: registrypullsecret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlpHVnljbUZwYm1Gb2J6cEZlRFF0TlZoeUxWbFdWaTAxWXpVPSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
